source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration // Edit this file to change your Hyprland configuration

exec-once = ~/.local/bin/waybar-launch
exec-once = ~/.local/bin/zen-warmup
