# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """\
  󰣇 \
  $directory\
  $git_branch$git_commit$git_state $git_status\
  $character\n
"""
right_format = """
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$pijul_channel\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$cpp\
$kotlin\
$ocaml\
$pixi\
$rlang\
$php\
$crystal\
$custom\
$status\
$os\
$time"""

continuation_prompt = '▶▶ '


# style_choices:
# bold
# italic
# underline
# dimmed
# inverted
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none

#NOTE: you can customize the symbols, e.g:
# [character]
# success_symbol = "[  ]($bold fg:#f8f8f2)"
# error_symbol = "[ ➤ ]($bold fg:#fb4934)"

[directory]
disabled = false
format = "[$path](bold fg:#8be9fd)"
truncate_to_repo = false
# home_symbol = "" 

[git_branch]
format = " [  $branch](fg:#9198a1)"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#769ff0)]($style)'
style = "bg:#394260"


[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb )]($style)'
time_format = "%R"                            # Hour:Minute Format

[deno]
format = " [deno](italic) [ ](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}]($style)"
style = "bold bright-yellow"
symbol = "⨀ "
version_format = "${raw}"

[nodejs]
detect_extensions = []
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
format = "[ ](bold bright-green)"
version_format = "${raw}"

[python]
format = "[${symbol}(${virtualenv}) ${version}]($style)"
style = "bold bright-yellow"
symbol = "[ ](bold bright-blue)"
version_format = "${raw}"

[ruby]
format = " [rb](italic) [${symbol}]($style)"
style = "bold red"
symbol = " "
version_format = "${raw}"

[rust]
style = "bold bright-red"
format = " rs(italic) $symbol($style)"
symbol = " "

[swift]
format = " [sw](italic) [${symbol}]($style)"
style = "bold bright-red"
symbol = " "
version_format = "${raw}"

[aws]
disabled = true
  format = " [$symbol aws]($style)"
style = "bold blue"
symbol = " "

[buf]
style = "bold bright-red"
  format = " [$symbol buf]($style)"
symbol = "■ "

[c]
style = "bold bright-cyan"
format = " [$symbol(-$name)]($style)"
symbol = "ℂ "

[cpp]
style = "bold bright-cyan"
  format = " [$symbol cpp]($style)"
symbol = "󰙲 "

[kotlin]
  format = " [$symbol kotlin]($style)"
style = "bold bright-red"
symbol = "󱈙 "

[ocaml]
  format = " [$symbol ocaml]($style)"
style = "bold bright-yellow"
symbol = "󰌟 "

[perl]
  format = " [$symbol perl]($style)"
style = "bold bright-cyan"
symbol = "󰏌 "

[php]
format = " [$symbol php]($style)"
style = "bold bright-red"
symbol = "󰌟 "

[pixi]
format = " [$symbol pixi]($style)"
style = "bold bright-yellow"
symbol = "󰧬 "

[rlang]
format = " [$symbol r]($style)"
style = "bold bright-cyan"
symbol = "󰟔 "

[meson]
format = " [$symbol meson]($style)"
style = "bold bright-red"
symbol = "󰒓 "

[conda]
style = "bold bright-red"
format = " conda [$symbol$environment]($style)"
symbol = "◯ "

[dart]
style = "bold bright-cyan"
format = " dart [$symbol]($style)"
symbol = " "


[elixir]
style = "bold bright-yellow"
format = " exs [$symbol OTP $otp_version ]($style)"
symbol = " "

[elm]
style = "bold bright-red"
format = " elm [$symbol]($style)"
symbol = "◩ "

[golang]
style = "bold bright-blue"
format = " go [$symbol]($style)"
symbol = "∩ "

[haskell]
style = "bold bright-yellow"
format = " hs [$symbol]($style)"
symbol = "❯λ "

[java]
style = "bold bright-red"
format = " java [${symbol}]($style)"
symbol = " "

[julia]
style = "bold bright-cyan"
format = " jl [$symbol]($style)"
symbol = "◎ "

[memory_usage]
style = "bold bright-cyan"
format = " mem [${ram}( ${swap})]($style)"
symbol = "▪▫▪ "

[nim]
style = "bold bright-yellow"
format = " nim [$symbol]($style)"
symbol = "▴▲▴ "

[nix_shell]
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
style = 'bold italic dimmed blue'
symbol = ' '
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
style = "bold bright-yellow"
format = " spack [$symbol$environment]($style)"
symbol = "◇ "


[zig]
style = "bold bright-yellow"
format = " zig [$symbol]($style)"
symbol = " "


[scala]
format = " scala [$symbol]($style)"
symbol = " "

[singularity]
format = " [$symbol singularity]($style)"
style = "bold bright-yellow"
symbol = "󰀈 "

[vcsh]
format = " [$symbol vcsh]($style)"
style = "bold bright-red"
symbol = "󰊤 "

[cobol]
format = " [$symbol cobol]($style)"
style = "bold bright-yellow"
symbol = "󰣄 "

[daml]
format = " [$symbol daml]($style)"
style = "bold bright-cyan"
symbol = "󰊢 "

[dotnet]
format = " [$symbol dotnet]($style)"
style = "bold bright-red"
symbol = "󰌮 "

[helm]
format = " [$symbol helm]($style)"
style = "bold bright-yellow"
symbol = "󰒓 "

[opa]
format = " [$symbol opa]($style)"
style = "bold bright-cyan"
symbol = "󰒓 "

[pulumi]
format = " [$symbol pulumi]($style)"
style = "bold bright-red"
  symbol = "󰜐 "

[raku]
format = " [$symbol raku]($style)"
style = "bold bright-cyan"
symbol = "󰏌 "

[red]
format = " [$symbol red]($style)"
style = "bold bright-red"
symbol = "󰆼 "

[terraform]
format = " [$symbol terraform]($style)"
style = "bold bright-cyan"
symbol = "󰜦 "

[vlang]
format = " [$symbol v]($style)"
style = "bold bright-red"
symbol = "󰌙 "

[vagrant]
format = " [$symbol vagrant]($style)"
style = "bold bright-yellow"
symbol = "󰜉 "

[gcloud]
format = " [$symbol gcloud]($style)"
style = "bold bright-cyan"
symbol = "󰳴 "

[openstack]
format = " [$symbol openstack]($style)"
style = "bold bright-red"
symbol = "󰌐 "

[azure]
  format = " [$symbol azure]($style)"
style = "bold bright-yellow"
symbol = " "

[crystal]
  format = " [$symbol crystal]($style)"
style = "bold bright-cyan"
symbol = " "
