#!/usr/bin/env zsh
export MOZ_ENABLE_WAYLAND=1

if [ -d /proc/driver/nvidia ]; then
    exec zen-twilight --no-sandbox "$@"
else
    exec zen-twilight --no-sandbox --disable-gpu --disable-software-rasterizer "$@"
fi
